# Generated by Django 4.1.3 on 2023-04-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0003_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='patient',
            name='social_work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Obra Social'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sw_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Obra Social'),
        ),
    ]
