# Generated by Django 4.1.3 on 2023-04-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0005_specialist_patient_address_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='medical_registration',
        ),
    ]
