# Generated by Django 4.1.3 on 2023-04-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0007_patient_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birth_day',
            new_name='date_of_birth',
        ),
    ]
