# Generated by Django 4.1.3 on 2023-05-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0008_rename_birth_day_patient_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
