# Generated by Django 4.2 on 2023-05-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0010_remove_doctor_birth_day_doctor_image_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre y Apellido'),
        ),
    ]
