# Generated by Django 4.1.3 on 2023-05-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0011_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
