# Generated by Django 4.1.3 on 2023-05-15 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0013_doctoravailability_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 30)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
