# Generated by Django 4.1.3 on 2023-05-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0017_alter_appointment_end_time_alter_doctor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_availability',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='clinica_app.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica_app.patient'),
        ),
    ]
