# Generated by Django 4.1.3 on 2023-05-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0021_alter_appointment_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorAvailability',
            new_name='Slot',
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('doctor', 'date', 'start_time', 'end_time')},
        ),
    ]
