# Generated by Django 4.2 on 2023-05-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0023_alter_slot_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_app.doctor'),
        ),
    ]
