# Generated by Django 4.2 on 2023-05-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0023_alter_appointment_patient'),
        ('clinica_app', '0024_alter_slot_doctor'),
    ]

    operations = [
    ]
