# Generated by Django 4.2.1 on 2023-06-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0025_merge_20230530_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
