# Generated by Django 4.2.1 on 2023-06-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0026_branch_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Branch_office')),
                ('doctors', models.ManyToManyField(to='clinica_app.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='Branch_offices',
        ),
    ]
