# Generated by Django 4.2.1 on 2023-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0028_remove_branch_office_doctors_doctor_branch_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='branch_office',
        ),
        migrations.AddField(
            model_name='doctor',
            name='branch_offices',
            field=models.ManyToManyField(related_name='doctors', to='clinica_app.branch_office'),
        ),
    ]
