# Generated by Django 4.2.1 on 2023-06-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0029_remove_doctor_branch_office_doctor_branch_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_office',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch_office',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
