# Generated by Django 4.1.3 on 2023-06-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0030_branch_office_address_branch_office_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('stand_by', 'Stand_by'), ('registered', 'Registered'), ('waiting', 'Waiting'), ('inside', 'Inside'), ('finished', 'Finished'), ('missed', 'Missed')], default='stand_by', max_length=20),
        ),
    ]
