# Generated by Django 4.1.3 on 2023-06-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0031_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='origin',
            field=models.CharField(choices=[('web', 'Web'), ('phone', 'Phone')], default='web', max_length=10),
        ),
    ]
