# Generated by Django 4.1.3 on 2023-04-28 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0004_remove_patient_email_remove_patient_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=20, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI')),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
                ('medical_registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Obra Social')),
                ('mr_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Obra Social')),
                ('birth_day', models.DateField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_app.specialist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
