# Generated by Django 4.1.3 on 2023-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0006_remove_doctor_medical_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ciudad'),
        ),
    ]
